services:
  - type: web
    name: contratos-pdf-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: ASPNETCORE_HTTP_PORT
        value: 8080
    healthCheckPath: /api/pdf/generate